[build.environment]
  NODE_VERSION = "20.19.0"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NEXT_PRIVATE_BUILD_WORKER = "1"

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
